//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TohumBankasiOtomasyonu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TohumBankasiOtomasyonu.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        internal static string BasariBaslik {
            get {
                return ResourceManager.GetString("BasariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki başarıyla kaydedildi..
        /// </summary>
        internal static string BitkiKayitBasarili {
            get {
                return ResourceManager.GetString("BitkiKayitBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Yönetimi.
        /// </summary>
        internal static string btnAdminBitkiler_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminBitkiler_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokzincir Verileri.
        /// </summary>
        internal static string btnAdminBlockchain_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminBlockchain_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        internal static string btnAdminKullanicilar_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminKullanicilar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        internal static string btnAdminPaneli_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminPaneli_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Kayıtları.
        /// </summary>
        internal static string btnAdminSatislar_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminSatislar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string btnBitkiKaydet {
            get {
                return ResourceManager.GetString("btnBitkiKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenli Çıkış.
        /// </summary>
        internal static string btnCikisYap_ToolTip {
            get {
                return ResourceManager.GetString("btnCikisYap_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        internal static string btnGiris_ToolTip {
            get {
                return ResourceManager.GetString("btnGiris_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string btnGirisYap_Text {
            get {
                return ResourceManager.GetString("btnGirisYap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileri Güncelle.
        /// </summary>
        internal static string btnHesapGuncelle {
            get {
                return ResourceManager.GetString("btnHesapGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnHesapTemizle_Text {
            get {
                return ResourceManager.GetString("btnHesapTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string btnKaydol_Text {
            get {
                return ResourceManager.GetString("btnKaydol_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız yok mu? Kayıt Olun.
        /// </summary>
        internal static string btnKayitOl_Text {
            get {
                return ResourceManager.GetString("btnKayitOl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnKayitTemizle_Text {
            get {
                return ResourceManager.GetString("btnKayitTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        internal static string btnKullaniciAyarlari_ToolTip {
            get {
                return ResourceManager.GetString("btnKullaniciAyarlari_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Seç....
        /// </summary>
        internal static string btnResimSec {
            get {
                return ResourceManager.GetString("btnResimSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnTemizle_Text {
            get {
                return ResourceManager.GetString("btnTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string ButonIptal {
            get {
                return ResourceManager.GetString("ButonIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string ButonSil {
            get {
                return ResourceManager.GetString("ButonSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yaptınız..
        /// </summary>
        internal static string CikisBasariliMesaj {
            get {
                return ResourceManager.GetString("CikisBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohum Bankası Otomasyonu.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Paneli.
        /// </summary>
        internal static string FormAdminPaneli_Title {
            get {
                return ResourceManager.GetString("FormAdminPaneli_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Düzenle.
        /// </summary>
        internal static string FormBitkiIslemleri_Title_Duzenle {
            get {
                return ResourceManager.GetString("FormBitkiIslemleri_Title_Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bitki Ekle.
        /// </summary>
        internal static string FormBitkiIslemleri_Title_Ekle {
            get {
                return ResourceManager.GetString("FormBitkiIslemleri_Title_Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        internal static string FormGiris_Title {
            get {
                return ResourceManager.GetString("FormGiris_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları.
        /// </summary>
        internal static string FormHesapAyarlari_Title {
            get {
                return ResourceManager.GetString("FormHesapAyarlari_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kaydı.
        /// </summary>
        internal static string FormKayitOl_Title {
            get {
                return ResourceManager.GetString("FormKayitOl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sırasında beklenmedik bir hata oluştu:.
        /// </summary>
        internal static string GenelHata {
            get {
                return ResourceManager.GetString("GenelHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ve şifre boş bırakılamaz..
        /// </summary>
        internal static string GirisAlanlarBosHata {
            get {
                return ResourceManager.GetString("GirisAlanlarBosHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz, {0} {1}! ({2}).
        /// </summary>
        internal static string GirisBasariliMesaj {
            get {
                return ResourceManager.GetString("GirisBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre hatalı..
        /// </summary>
        internal static string GirisHataliMesaj {
            get {
                return ResourceManager.GetString("GirisHataliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz başarıyla güncellendi..
        /// </summary>
        internal static string GuncellemeBasarili {
            get {
                return ResourceManager.GetString("GuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string HataBaslik {
            get {
                return ResourceManager.GetString("HataBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bitkinin Bilimsel Adını giriniz..
        /// </summary>
        internal static string HataBilimselAd {
            get {
                return ResourceManager.GetString("HataBilimselAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Türkçe bitki adını giriniz..
        /// </summary>
        internal static string HataBitkiAdi {
            get {
                return ResourceManager.GetString("HataBitkiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki fiyatı 0&apos;dan büyük olmalıdır..
        /// </summary>
        internal static string HataBitkiFiyat {
            get {
                return ResourceManager.GetString("HataBitkiFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir bitki görseli seçiniz..
        /// </summary>
        internal static string HataBitkiResim {
            get {
                return ResourceManager.GetString("HataBitkiResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı Sil.
        /// </summary>
        internal static string HesapSilUyariBaslik {
            get {
                return ResourceManager.GetString("HesapSilUyariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız kalıcı olarak ve geri döndürülemez şekilde silinecektir. Bu işlemi yapmak istediğinizden emin misiniz?.
        /// </summary>
        internal static string HesapSilUyariMesaj {
            get {
                return ResourceManager.GetString("HesapSilUyariMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydınız başarıyla tamamlandı. Şimdi giriş yapabilirsiniz..
        /// </summary>
        internal static string KayitBasariliMesaj {
            get {
                return ResourceManager.GetString("KayitBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı zaten alınmış. Lütfen farklı bir kullanıcı adı deneyin..
        /// </summary>
        internal static string KullaniciAdiMevcutHata {
            get {
                return ResourceManager.GetString("KullaniciAdiMevcutHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:.
        /// </summary>
        internal static string labelHesapAd {
            get {
                return ResourceManager.GetString("labelHesapAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        internal static string labelHesapEmail {
            get {
                return ResourceManager.GetString("labelHesapEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string labelHesapKullaniciAdi {
            get {
                return ResourceManager.GetString("labelHesapKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Şifre: .
        /// </summary>
        internal static string labelHesapMevcutSifre {
            get {
                return ResourceManager.GetString("labelHesapMevcutSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:.
        /// </summary>
        internal static string labelHesapSoyad {
            get {
                return ResourceManager.GetString("labelHesapSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre:.
        /// </summary>
        internal static string labelHesapYeniSifre {
            get {
                return ResourceManager.GetString("labelHesapYeniSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Tekrar:.
        /// </summary>
        internal static string labelHesapYeniSifreTekrar {
            get {
                return ResourceManager.GetString("labelHesapYeniSifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:*.
        /// </summary>
        internal static string labelKayitAd {
            get {
                return ResourceManager.GetString("labelKayitAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        internal static string labelKayitEmail {
            get {
                return ResourceManager.GetString("labelKayitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı: *.
        /// </summary>
        internal static string labelKayitKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKayitKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre: *.
        /// </summary>
        internal static string labelKayitSifre {
            get {
                return ResourceManager.GetString("labelKayitSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar: *.
        /// </summary>
        internal static string labelKayitSifreTekrar {
            get {
                return ResourceManager.GetString("labelKayitSifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:*.
        /// </summary>
        internal static string labelKayitSoyad {
            get {
                return ResourceManager.GetString("labelKayitSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string labelKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string labelSifre {
            get {
                return ResourceManager.GetString("labelSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        internal static string lblBitkiAciklama {
            get {
                return ResourceManager.GetString("lblBitkiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Adı:.
        /// </summary>
        internal static string lblBitkiAdi {
            get {
                return ResourceManager.GetString("lblBitkiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilimsel Adı (Latince):.
        /// </summary>
        internal static string lblBitkiBilimselAd {
            get {
                return ResourceManager.GetString("lblBitkiBilimselAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat (₺):.
        /// </summary>
        internal static string lblBitkiFiyat {
            get {
                return ResourceManager.GetString("lblBitkiFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Görseli:.
        /// </summary>
        internal static string lblBitkiResim {
            get {
                return ResourceManager.GetString("lblBitkiResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saklama Koşulları:.
        /// </summary>
        internal static string lblBitkiSaklama {
            get {
                return ResourceManager.GetString("lblBitkiSaklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Adedi:.
        /// </summary>
        internal static string lblBitkiStok {
            get {
                return ResourceManager.GetString("lblBitkiStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetiştirme Koşulları:.
        /// </summary>
        internal static string lblBitkiYetistirme {
            get {
                return ResourceManager.GetString("lblBitkiYetistirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabımı Kalıcı Olarak Kapat.
        /// </summary>
        internal static string linkHesapSil {
            get {
                return ResourceManager.GetString("linkHesapSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri kaydetmek için girdiğiniz mevcut şifre hatalı..
        /// </summary>
        internal static string MevcutSifreHatali {
            get {
                return ResourceManager.GetString("MevcutSifreHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyaları|*.jpg;*.jpeg;*.png;*.bmp;*.gif.
        /// </summary>
        internal static string ResimSecDialogFilter {
            get {
                return ResourceManager.GetString("ResimSecDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Görseli Seç.
        /// </summary>
        internal static string ResimSecDialogTitle {
            get {
                return ResourceManager.GetString("ResimSecDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim yüklenirken bir hata oluştu:.
        /// </summary>
        internal static string ResimYuklemeHata {
            get {
                return ResourceManager.GetString("ResimYuklemeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz şifreler birbiriyle eşleşmiyor..
        /// </summary>
        internal static string SifreEslesmeHata {
            get {
                return ResourceManager.GetString("SifreEslesmeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Bilgiler.
        /// </summary>
        internal static string tabBitkiEN {
            get {
                return ResourceManager.GetString("tabBitkiEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Bilgiler.
        /// </summary>
        internal static string tabBitkiTR {
            get {
                return ResourceManager.GetString("tabBitkiTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string UserType_Admin {
            get {
                return ResourceManager.GetString("UserType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        internal static string UserType_Kullanici {
            get {
                return ResourceManager.GetString("UserType_Kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıldızlı (*) alanların tamamı doldurulmalıdır..
        /// </summary>
        internal static string ZorunluAlanlarHata {
            get {
                return ResourceManager.GetString("ZorunluAlanlarHata", resourceCulture);
            }
        }
    }
}
