//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TohumBankasiOtomasyonu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TohumBankasiOtomasyonu.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        public static string BasariBaslik {
            get {
                return ResourceManager.GetString("BasariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAKLAMA:.
        /// </summary>
        public static string BaslikSaklama {
            get {
                return ResourceManager.GetString("BaslikSaklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string BaslikSil {
            get {
                return ResourceManager.GetString("BaslikSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YETİŞTİRME:.
        /// </summary>
        public static string BaslikYetistirme {
            get {
                return ResourceManager.GetString("BaslikYetistirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki başarıyla kaydedildi..
        /// </summary>
        public static string BitkiKayitBasarili {
            get {
                return ResourceManager.GetString("BitkiKayitBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki başarıyla silindi..
        /// </summary>
        public static string BitkiSilBasarili {
            get {
                return ResourceManager.GetString("BitkiSilBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme Onayı.
        /// </summary>
        public static string BitkiSilOnayBaslik {
            get {
                return ResourceManager.GetString("BitkiSilOnayBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili bitkiyi silmek istediğinize emin misiniz?.
        /// </summary>
        public static string BitkiSilOnayMesaj {
            get {
                return ResourceManager.GetString("BitkiSilOnayMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış ID: {0}, Tutar: {1}, Tarih: {2}.
        /// </summary>
        public static string BlokzincirVerisi {
            get {
                return ResourceManager.GetString("BlokzincirVerisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Yönetimi.
        /// </summary>
        public static string btnAdminBitkiler_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminBitkiler_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokzincir Verileri.
        /// </summary>
        public static string btnAdminBlockchain_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminBlockchain_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Yönetimi.
        /// </summary>
        public static string btnAdminKullanicilar_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminKullanicilar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Paneli.
        /// </summary>
        public static string btnAdminPaneli_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminPaneli_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Kayıtları.
        /// </summary>
        public static string btnAdminSatislar_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminSatislar_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Yönetimi.
        /// </summary>
        public static string btnAdminStok_ToolTip {
            get {
                return ResourceManager.GetString("btnAdminStok_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string btnAnaSayfa_ToolTip {
            get {
                return ResourceManager.GetString("btnAnaSayfa_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Bitki Asistanı.
        /// </summary>
        public static string btnAsistan_ToolTip {
            get {
                return ResourceManager.GetString("btnAsistan_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiz Et / Gönder.
        /// </summary>
        public static string btnAsistanAnaliz {
            get {
                return ResourceManager.GetString("btnAsistanAnaliz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf Yükle....
        /// </summary>
        public static string btnAsistanResimSec {
            get {
                return ResourceManager.GetString("btnAsistanResimSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Ara / Bilgi Bankası.
        /// </summary>
        public static string btnBitkiBilgi_ToolTip {
            get {
                return ResourceManager.GetString("btnBitkiBilgi_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar ve Sohbet.
        /// </summary>
        public static string btnBitkiDetay_ToolTip {
            get {
                return ResourceManager.GetString("btnBitkiDetay_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string btnBitkiKaydet {
            get {
                return ResourceManager.GetString("btnBitkiKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitkilerim / Bahçem.
        /// </summary>
        public static string btnBitkilerim_ToolTip {
            get {
                return ResourceManager.GetString("btnBitkilerim_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitkiyi Sil.
        /// </summary>
        public static string btnBitkiSil_ToolTip {
            get {
                return ResourceManager.GetString("btnBitkiSil_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenli Çıkış.
        /// </summary>
        public static string btnCikisYap_ToolTip {
            get {
                return ResourceManager.GetString("btnCikisYap_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Arşivi.
        /// </summary>
        public static string btnGecmisRaporlar {
            get {
                return ResourceManager.GetString("btnGecmisRaporlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        public static string btnGiris_ToolTip {
            get {
                return ResourceManager.GetString("btnGiris_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string btnGirisYap_Text {
            get {
                return ResourceManager.GetString("btnGirisYap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string btnHakkinda_ToolTip {
            get {
                return ResourceManager.GetString("btnHakkinda_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileri Güncelle.
        /// </summary>
        public static string btnHesapGuncelle {
            get {
                return ResourceManager.GetString("btnHesapGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string btnHesapTemizle_Text {
            get {
                return ResourceManager.GetString("btnHesapTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string btnKapat {
            get {
                return ResourceManager.GetString("btnKapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string btnKaydol_Text {
            get {
                return ResourceManager.GetString("btnKaydol_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız yok mu? Kayıt Olun.
        /// </summary>
        public static string btnKayitOl_Text {
            get {
                return ResourceManager.GetString("btnKayitOl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string btnKayitTemizle_Text {
            get {
                return ResourceManager.GetString("btnKayitTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string btnKeyGuncelle {
            get {
                return ResourceManager.GetString("btnKeyGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string btnKeyKaydet {
            get {
                return ResourceManager.GetString("btnKeyKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        public static string btnKullaniciAyarlari_ToolTip {
            get {
                return ResourceManager.GetString("btnKullaniciAyarlari_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string btnKullaniciGuncelle {
            get {
                return ResourceManager.GetString("btnKullaniciGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Oluştur.
        /// </summary>
        public static string btnRaporAl_Text {
            get {
                return ResourceManager.GetString("btnRaporAl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf Ekle.
        /// </summary>
        public static string btnResimEkle_Text {
            get {
                return ResourceManager.GetString("btnResimEkle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Seç....
        /// </summary>
        public static string btnResimSec {
            get {
                return ResourceManager.GetString("btnResimSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detayları Gör.
        /// </summary>
        public static string btnSatisDetay_Text {
            get {
                return ResourceManager.GetString("btnSatisDetay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetim.
        /// </summary>
        public static string btnSepet_ToolTip {
            get {
                return ResourceManager.GetString("btnSepet_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Almayı Tamamla.
        /// </summary>
        public static string btnSepetSatinAl {
            get {
                return ResourceManager.GetString("btnSepetSatinAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti Boşalt.
        /// </summary>
        public static string btnSepetTemizle {
            get {
                return ResourceManager.GetString("btnSepetTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili Ürünü Çıkar.
        /// </summary>
        public static string btnSepetUrunSil {
            get {
                return ResourceManager.GetString("btnSepetUrunSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Siparişlerim.
        /// </summary>
        public static string btnSiparisGecmisi_ToolTip {
            get {
                return ResourceManager.GetString("btnSiparisGecmisi_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takibi Başlat.
        /// </summary>
        public static string btnTakipBaslat {
            get {
                return ResourceManager.GetString("btnTakipBaslat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        public static string btnTemizle_Text {
            get {
                return ResourceManager.GetString("btnTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bitki Takibi Başlat.
        /// </summary>
        public static string btnYeniTakipEkle {
            get {
                return ResourceManager.GetString("btnYeniTakipEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string ButonIptal {
            get {
                return ResourceManager.GetString("ButonIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ButonSil {
            get {
                return ResourceManager.GetString("ButonSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏳ Analiz yapılıyor, lütfen bekleyin....
        /// </summary>
        public static string ChatDurum_Bekleyin {
            get {
                return ResourceManager.GetString("ChatDurum_Bekleyin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEMINI:.
        /// </summary>
        public static string ChatSender_AI {
            get {
                return ResourceManager.GetString("ChatSender_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİZ:.
        /// </summary>
        public static string ChatSender_User {
            get {
                return ResourceManager.GetString("ChatSender_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yaptınız..
        /// </summary>
        public static string CikisBasariliMesaj {
            get {
                return ResourceManager.GetString("CikisBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Fiyat.
        /// </summary>
        public static string colBirimFiyat {
            get {
                return ResourceManager.GetString("colBirimFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Adı.
        /// </summary>
        public static string colBitkiAdi {
            get {
                return ResourceManager.GetString("colBitkiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilimsel Ad.
        /// </summary>
        public static string colBitkiBilimsel {
            get {
                return ResourceManager.GetString("colBitkiBilimsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string colBitkiDurum {
            get {
                return ResourceManager.GetString("colBitkiDurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string colBitkiFiyat {
            get {
                return ResourceManager.GetString("colBitkiFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string colBitkiID {
            get {
                return ResourceManager.GetString("colBitkiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok.
        /// </summary>
        public static string colBitkiStok {
            get {
                return ResourceManager.GetString("colBitkiStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok No.
        /// </summary>
        public static string colBlokID {
            get {
                return ResourceManager.GetString("colBlokID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilimsel Ad.
        /// </summary>
        public static string colDetayBilimselAd {
            get {
                return ResourceManager.GetString("colDetayBilimselAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görsel.
        /// </summary>
        public static string colDetayResim {
            get {
                return ResourceManager.GetString("colDetayResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string colGecmisDurum {
            get {
                return ResourceManager.GetString("colGecmisDurum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makbuz No.
        /// </summary>
        public static string colGecmisMakbuz {
            get {
                return ResourceManager.GetString("colGecmisMakbuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string colGecmisTarih {
            get {
                return ResourceManager.GetString("colGecmisTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string colGecmisTutar {
            get {
                return ResourceManager.GetString("colGecmisTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string colKullaniciAd {
            get {
                return ResourceManager.GetString("colKullaniciAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string colKullaniciAdi {
            get {
                return ResourceManager.GetString("colKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string colKullaniciEmail {
            get {
                return ResourceManager.GetString("colKullaniciEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string colKullaniciID {
            get {
                return ResourceManager.GetString("colKullaniciID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string colKullaniciSoyad {
            get {
                return ResourceManager.GetString("colKullaniciSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string colKullaniciYetki {
            get {
                return ResourceManager.GetString("colKullaniciYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok Hash&apos;i.
        /// </summary>
        public static string colMevcutHash {
            get {
                return ResourceManager.GetString("colMevcutHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string colMiktar {
            get {
                return ResourceManager.GetString("colMiktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        public static string colMusteriAdSoyad {
            get {
                return ResourceManager.GetString("colMusteriAdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki Hash.
        /// </summary>
        public static string colOncekiHash {
            get {
                return ResourceManager.GetString("colOncekiHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndir.
        /// </summary>
        public static string colRaporIndir {
            get {
                return ResourceManager.GetString("colRaporIndir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string colRaporTarih {
            get {
                return ResourceManager.GetString("colRaporTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Toplam.
        /// </summary>
        public static string colSatirToplam {
            get {
                return ResourceManager.GetString("colSatirToplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makbuz No.
        /// </summary>
        public static string colSatisId {
            get {
                return ResourceManager.GetString("colSatisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makbuz No.
        /// </summary>
        public static string colSatisMakbuz {
            get {
                return ResourceManager.GetString("colSatisMakbuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        public static string colSatisMusteri {
            get {
                return ResourceManager.GetString("colSatisMusteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string colSatisTarih {
            get {
                return ResourceManager.GetString("colSatisTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string colSatisTutar {
            get {
                return ResourceManager.GetString("colSatisTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet.
        /// </summary>
        public static string colSepetAdet {
            get {
                return ResourceManager.GetString("colSepetAdet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Fiyat.
        /// </summary>
        public static string colSepetFiyat {
            get {
                return ResourceManager.GetString("colSepetFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Görseli.
        /// </summary>
        public static string colSepetResim {
            get {
                return ResourceManager.GetString("colSepetResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string colSepetToplam {
            get {
                return ResourceManager.GetString("colSepetToplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string colSepetUrunAdi {
            get {
                return ResourceManager.GetString("colSepetUrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string colToplamTutar {
            get {
                return ResourceManager.GetString("colToplamTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string colUrunAdi {
            get {
                return ResourceManager.GetString("colUrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri / İşlem.
        /// </summary>
        public static string colVeri {
            get {
                return ResourceManager.GetString("colVeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaman Damgası.
        /// </summary>
        public static string colZamanDamgasi {
            get {
                return ResourceManager.GetString("colZamanDamgasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bekleyin, Gemini bitkinizi inceliyor....
        /// </summary>
        public static string DurumAnalizEdiliyor {
            get {
                return ResourceManager.GetString("DurumAnalizEdiliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohum Bankası Otomasyonu.
        /// </summary>
        public static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Paneli.
        /// </summary>
        public static string FormAdminPaneli_Title {
            get {
                return ResourceManager.GetString("FormAdminPaneli_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Düzenle.
        /// </summary>
        public static string FormBitkiIslemleri_Title_Duzenle {
            get {
                return ResourceManager.GetString("FormBitkiIslemleri_Title_Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bitki Ekle.
        /// </summary>
        public static string FormBitkiIslemleri_Title_Ekle {
            get {
                return ResourceManager.GetString("FormBitkiIslemleri_Title_Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        public static string FormGiris_Title {
            get {
                return ResourceManager.GetString("FormGiris_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Hakkında.
        /// </summary>
        public static string FormHakkinda_Title {
            get {
                return ResourceManager.GetString("FormHakkinda_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları.
        /// </summary>
        public static string FormHesapAyarlari_Title {
            get {
                return ResourceManager.GetString("FormHesapAyarlari_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kaydı.
        /// </summary>
        public static string FormKayitOl_Title {
            get {
                return ResourceManager.GetString("FormKayitOl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Düzenle.
        /// </summary>
        public static string FormKullaniciDuzenle_Title {
            get {
                return ResourceManager.GetString("FormKullaniciDuzenle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlarım.
        /// </summary>
        public static string FormRaporListesi_Title {
            get {
                return ResourceManager.GetString("FormRaporListesi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Görseli.
        /// </summary>
        public static string FormResimGoruntule_Title {
            get {
                return ResourceManager.GetString("FormResimGoruntule_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Detayları.
        /// </summary>
        public static string FormSatisDetay_Title {
            get {
                return ResourceManager.GetString("FormSatisDetay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepeti.
        /// </summary>
        public static string FormSepet_Title {
            get {
                return ResourceManager.GetString("FormSepet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Geçmişi.
        /// </summary>
        public static string FormSiparisGecmisi_Title {
            get {
                return ResourceManager.GetString("FormSiparisGecmisi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bitki Takibi.
        /// </summary>
        public static string FormYeniBitkiEkle_Title {
            get {
                return ResourceManager.GetString("FormYeniBitkiEkle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sırasında beklenmedik bir hata oluştu:.
        /// </summary>
        public static string GenelHata {
            get {
                return ResourceManager.GetString("GenelHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ve şifre boş bırakılamaz..
        /// </summary>
        public static string GirisAlanlarBosHata {
            get {
                return ResourceManager.GetString("GirisAlanlarBosHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz, {0} {1}! ({2}).
        /// </summary>
        public static string GirisBasariliMesaj {
            get {
                return ResourceManager.GetString("GirisBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre hatalı..
        /// </summary>
        public static string GirisHataliMesaj {
            get {
                return ResourceManager.GetString("GirisHataliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz başarıyla güncellendi..
        /// </summary>
        public static string GuncellemeBasarili {
            get {
                return ResourceManager.GetString("GuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string HataBaslik {
            get {
                return ResourceManager.GetString("HataBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bitkinin Bilimsel Adını giriniz..
        /// </summary>
        public static string HataBilimselAd {
            get {
                return ResourceManager.GetString("HataBilimselAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Türkçe bitki adını giriniz..
        /// </summary>
        public static string HataBitkiAdi {
            get {
                return ResourceManager.GetString("HataBitkiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki fiyatı 0&apos;dan büyük olmalıdır..
        /// </summary>
        public static string HataBitkiFiyat {
            get {
                return ResourceManager.GetString("HataBitkiFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir bitki görseli seçiniz..
        /// </summary>
        public static string HataBitkiResim {
            get {
                return ResourceManager.GetString("HataBitkiResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henüz takip ettiğiniz bir bitki yok..
        /// </summary>
        public static string HataBitkiYok {
            get {
                return ResourceManager.GetString("HataBitkiYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete ürün eklemek için lütfen giriş yapınız..
        /// </summary>
        public static string HataGirisGerekli {
            get {
                return ResourceManager.GetString("HataGirisGerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce bir API Anahtarı girip kaydedin..
        /// </summary>
        public static string HataKeyEksik {
            get {
                return ResourceManager.GetString("HataKeyEksik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen analiz edilecek bir bitki fotoğrafı seçiniz..
        /// </summary>
        public static string HataResimSecilmedi {
            get {
                return ResourceManager.GetString("HataResimSecilmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silinecek bir satır seçiniz..
        /// </summary>
        public static string HataSatirSecilmedi {
            get {
                return ResourceManager.GetString("HataSatirSecilmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti görüntülemek için giriş yapmalısınız..
        /// </summary>
        public static string HataSepetGoruntuleme {
            get {
                return ResourceManager.GetString("HataSepetGoruntuleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir resim yükleyin veya bir soru yazın..
        /// </summary>
        public static string HataSoruVeyaResimEksik {
            get {
                return ResourceManager.GetString("HataSoruVeyaResimEksik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bitkinize bir isim verin..
        /// </summary>
        public static string HataTakipAd {
            get {
                return ResourceManager.GetString("HataTakipAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen takip edilecek bitkinin fotoğrafını yükleyin..
        /// </summary>
        public static string HataTakipResim {
            get {
                return ResourceManager.GetString("HataTakipResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetersiz stok! Şu ürün tükenmiş:.
        /// </summary>
        public static string HataYetersizStok {
            get {
                return ResourceManager.GetString("HataYetersizStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabı Sil.
        /// </summary>
        public static string HesapSilUyariBaslik {
            get {
                return ResourceManager.GetString("HesapSilUyariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız kalıcı olarak ve geri döndürülemez şekilde silinecektir. Bu işlemi yapmak istediğinizden emin misiniz?.
        /// </summary>
        public static string HesapSilUyariMesaj {
            get {
                return ResourceManager.GetString("HesapSilUyariMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydınız başarıyla tamamlandı. Şimdi giriş yapabilirsiniz..
        /// </summary>
        public static string KayitBasariliMesaj {
            get {
                return ResourceManager.GetString("KayitBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı zaten alınmış. Lütfen farklı bir kullanıcı adı deneyin..
        /// </summary>
        public static string KullaniciAdiMevcutHata {
            get {
                return ResourceManager.GetString("KullaniciAdiMevcutHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı başarıyla silindi..
        /// </summary>
        public static string KullaniciSilBasarili {
            get {
                return ResourceManager.GetString("KullaniciSilBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Silme Onayı.
        /// </summary>
        public static string KullaniciSilOnayBaslik {
            get {
                return ResourceManager.GetString("KullaniciSilOnayBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili kullanıcıyı kalıcı olarak silmek istediğinize emin misiniz?.
        /// </summary>
        public static string KullaniciSilOnayMesaj {
            get {
                return ResourceManager.GetString("KullaniciSilOnayMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:.
        /// </summary>
        public static string labelHesapAd {
            get {
                return ResourceManager.GetString("labelHesapAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        public static string labelHesapEmail {
            get {
                return ResourceManager.GetString("labelHesapEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        public static string labelHesapKullaniciAdi {
            get {
                return ResourceManager.GetString("labelHesapKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Şifre: .
        /// </summary>
        public static string labelHesapMevcutSifre {
            get {
                return ResourceManager.GetString("labelHesapMevcutSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:.
        /// </summary>
        public static string labelHesapSoyad {
            get {
                return ResourceManager.GetString("labelHesapSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre:.
        /// </summary>
        public static string labelHesapYeniSifre {
            get {
                return ResourceManager.GetString("labelHesapYeniSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Tekrar:.
        /// </summary>
        public static string labelHesapYeniSifreTekrar {
            get {
                return ResourceManager.GetString("labelHesapYeniSifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:*.
        /// </summary>
        public static string labelKayitAd {
            get {
                return ResourceManager.GetString("labelKayitAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        public static string labelKayitEmail {
            get {
                return ResourceManager.GetString("labelKayitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı: *.
        /// </summary>
        public static string labelKayitKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKayitKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre: *.
        /// </summary>
        public static string labelKayitSifre {
            get {
                return ResourceManager.GetString("labelKayitSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar: *.
        /// </summary>
        public static string labelKayitSifreTekrar {
            get {
                return ResourceManager.GetString("labelKayitSifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:*.
        /// </summary>
        public static string labelKayitSoyad {
            get {
                return ResourceManager.GetString("labelKayitSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        public static string labelKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        public static string labelSifre {
            get {
                return ResourceManager.GetString("labelSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu program, bitki tohumlarının takibi, satışı ve blokzincir tabanlı güvenli kaydı için geliştirilmiştir..
        /// </summary>
        public static string lblAciklama {
            get {
                return ResourceManager.GetString("lblAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini API Anahtarı:.
        /// </summary>
        public static string lblApiKeyBaslik {
            get {
                return ResourceManager.GetString("lblApiKeyBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohum Bankasında Ara....
        /// </summary>
        public static string lblAramaBaslik {
            get {
                return ResourceManager.GetString("lblAramaBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapay Zeka Bitki Analizi.
        /// </summary>
        public static string lblAsistanBaslik {
            get {
                return ResourceManager.GetString("lblAsistanBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aradığınız kriterlere uygun bitki bulunamadı..
        /// </summary>
        public static string lblBilgiBulunamadi {
            get {
                return ResourceManager.GetString("lblBilgiBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string lblBitkiAciklama {
            get {
                return ResourceManager.GetString("lblBitkiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Adı:.
        /// </summary>
        public static string lblBitkiAdi {
            get {
                return ResourceManager.GetString("lblBitkiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilimsel Adı (Latince):.
        /// </summary>
        public static string lblBitkiBilimselAd {
            get {
                return ResourceManager.GetString("lblBitkiBilimselAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat (₺):.
        /// </summary>
        public static string lblBitkiFiyat {
            get {
                return ResourceManager.GetString("lblBitkiFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takip Ettiğim Bitkiler.
        /// </summary>
        public static string lblBitkilerimBaslik {
            get {
                return ResourceManager.GetString("lblBitkilerimBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Görseli:.
        /// </summary>
        public static string lblBitkiResim {
            get {
                return ResourceManager.GetString("lblBitkiResim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saklama Koşulları:.
        /// </summary>
        public static string lblBitkiSaklama {
            get {
                return ResourceManager.GetString("lblBitkiSaklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Adedi:.
        /// </summary>
        public static string lblBitkiStok {
            get {
                return ResourceManager.GetString("lblBitkiStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetiştirme Koşulları:.
        /// </summary>
        public static string lblBitkiYetistirme {
            get {
                return ResourceManager.GetString("lblBitkiYetistirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini AI Cevabı:.
        /// </summary>
        public static string lblCevapBaslik {
            get {
                return ResourceManager.GetString("lblCevapBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makbuz No:.
        /// </summary>
        public static string lblDetayMakbuzNo {
            get {
                return ResourceManager.GetString("lblDetayMakbuzNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string lblDetayTarih {
            get {
                return ResourceManager.GetString("lblDetayTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Toplam:.
        /// </summary>
        public static string lblDetayToplam {
            get {
                return ResourceManager.GetString("lblDetayToplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geliştirici: [Murat Gül].
        /// </summary>
        public static string lblGelistirici {
            get {
                return ResourceManager.GetString("lblGelistirici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki / Rol:.
        /// </summary>
        public static string lblKullaniciTipi {
            get {
                return ResourceManager.GetString("lblKullaniciTipi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohum Bankası Otomasyonu.
        /// </summary>
        public static string lblProjeAdi {
            get {
                return ResourceManager.GetString("lblProjeAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Toplam:.
        /// </summary>
        public static string lblSepetGenelToplam {
            get {
                return ResourceManager.GetString("lblSepetGenelToplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitkiniz hakkında ne sormak istersiniz?.
        /// </summary>
        public static string lblSoruBaslik {
            get {
                return ResourceManager.GetString("lblSoruBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitkine Bir İsim Ver:.
        /// </summary>
        public static string lblTakipAdi {
            get {
                return ResourceManager.GetString("lblTakipAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 Tüm Hakları Saklıdır..
        /// </summary>
        public static string lblTelif {
            get {
                return ResourceManager.GetString("lblTelif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Not: Yapay zeka bir önceki sorunuzu hatırlamaz. Lütfen sorunuzu tek seferde ve detaylı sorunuz..
        /// </summary>
        public static string LblUyariHafiza {
            get {
                return ResourceManager.GetString("LblUyariHafiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürüm: 1.0.0.
        /// </summary>
        public static string lblVersiyon {
            get {
                return ResourceManager.GetString("lblVersiyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google API Anahtarı Al (Ücretsiz).
        /// </summary>
        public static string linkApiKeyAl {
            get {
                return ResourceManager.GetString("linkApiKeyAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabımı Kalıcı Olarak Kapat.
        /// </summary>
        public static string linkHesapSil {
            get {
                return ResourceManager.GetString("linkHesapSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri kaydetmek için girdiğiniz mevcut şifre hatalı..
        /// </summary>
        public static string MevcutSifreHatali {
            get {
                return ResourceManager.GetString("MevcutSifreHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Anahtarınızı buraya girin....
        /// </summary>
        public static string MsgKeyGirin {
            get {
                return ResourceManager.GetString("MsgKeyGirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Anahtarı başarıyla kaydedildi!.
        /// </summary>
        public static string MsgKeyKaydedildi {
            get {
                return ResourceManager.GetString("MsgKeyKaydedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********** (Kayıtlı).
        /// </summary>
        public static string MsgKeyMevcut {
            get {
                return ResourceManager.GetString("MsgKeyMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor başarıyla oluşturuldu..
        /// </summary>
        public static string MsgRaporBasarili {
            get {
                return ResourceManager.GetString("MsgRaporBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF raporu başarıyla indirildi.
        /// </summary>
        public static string MsgRaporIndirildi {
            get {
                return ResourceManager.GetString("MsgRaporIndirildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu resmi kaldırmak istiyor musunuz?.
        /// </summary>
        public static string MsgResimSilOnay {
            get {
                return ResourceManager.GetString("MsgResimSilOnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetiniz şu an boş..
        /// </summary>
        public static string MsgSepetBos {
            get {
                return ResourceManager.GetString("MsgSepetBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün sepete eklendi!.
        /// </summary>
        public static string MsgSepeteEklandi {
            get {
                return ResourceManager.GetString("MsgSepeteEklandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string OnayBaslik {
            get {
                return ResourceManager.GetString("OnayBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti tamamen boşaltmak istediğinize emin misiniz?.
        /// </summary>
        public static string OnaySepetBosalt {
            get {
                return ResourceManager.GetString("OnaySepetBosalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\n(Lütfen bu bilgilere ve görsellere dayanarak, bitkinin durumu hakkında başlıklar halinde DETAYLI BİR DURUM RAPORU oluştur.).
        /// </summary>
        public static string Promt_RaporEki {
            get {
                return ResourceManager.GetString("Promt_RaporEki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu bitkiyle ilgili şu ana kadar konuştuğumuz her şeyi ve gönderdiğim resimleri analiz ederek bana detaylı bir GELİŞİM RAPORU hazırla..
        /// </summary>
        public static string Promt_RaporIstegi {
            get {
                return ResourceManager.GetString("Promt_RaporIstegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Dosyaları|*.jpg;*.jpeg;*.png;*.bmp;*.gif.
        /// </summary>
        public static string ResimSecDialogFilter {
            get {
                return ResourceManager.GetString("ResimSecDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitki Görseli Seç.
        /// </summary>
        public static string ResimSecDialogTitle {
            get {
                return ResourceManager.GetString("ResimSecDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim yüklenirken bir hata oluştu:.
        /// </summary>
        public static string ResimYuklemeHata {
            get {
                return ResourceManager.GetString("ResimYuklemeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string Role_Kullanici {
            get {
                return ResourceManager.GetString("Role_Kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın alma işlemi başarıyla tamamlandı ve Blokzincire işlendi!.
        /// </summary>
        public static string SatinAlmaBasarili {
            get {
                return ResourceManager.GetString("SatinAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz şifreler birbiriyle eşleşmiyor..
        /// </summary>
        public static string SifreEslesmeHata {
            get {
                return ResourceManager.GetString("SifreEslesmeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce Bilgiler.
        /// </summary>
        public static string tabBitkiEN {
            get {
                return ResourceManager.GetString("tabBitkiEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe Bilgiler.
        /// </summary>
        public static string tabBitkiTR {
            get {
                return ResourceManager.GetString("tabBitkiTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Bilgiler.
        /// </summary>
        public static string tabGenelBilgi {
            get {
                return ResourceManager.GetString("tabGenelBilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetiştirme ve Saklama.
        /// </summary>
        public static string tabTeknikBilgi {
            get {
                return ResourceManager.GetString("tabTeknikBilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserType_Admin {
            get {
                return ResourceManager.GetString("UserType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string UserType_Kullanici {
            get {
                return ResourceManager.GetString("UserType_Kullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UyariBaslik {
            get {
                return ResourceManager.GetString("UyariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıldızlı (*) alanların tamamı doldurulmalıdır..
        /// </summary>
        public static string ZorunluAlanlarHata {
            get {
                return ResourceManager.GetString("ZorunluAlanlarHata", resourceCulture);
            }
        }
    }
}
