//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TohumBankasiOtomasyonu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TohumBankasiOtomasyonu.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı.
        /// </summary>
        internal static string BasariBaslik {
            get {
                return ResourceManager.GetString("BasariBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        internal static string btnGiris_ToolTip {
            get {
                return ResourceManager.GetString("btnGiris_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string btnGirisYap_Text {
            get {
                return ResourceManager.GetString("btnGirisYap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string btnKaydol_Text {
            get {
                return ResourceManager.GetString("btnKaydol_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız yok mu? Kayıt Olun.
        /// </summary>
        internal static string btnKayitOl_Text {
            get {
                return ResourceManager.GetString("btnKayitOl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnKayitTemizle_Text {
            get {
                return ResourceManager.GetString("btnKayitTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnTemizle_Text {
            get {
                return ResourceManager.GetString("btnTemizle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohum Bankası Otomasyonu.
        /// </summary>
        internal static string Form1_Title {
            get {
                return ResourceManager.GetString("Form1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        internal static string FormGiris_Title {
            get {
                return ResourceManager.GetString("FormGiris_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Kaydı.
        /// </summary>
        internal static string FormKayitOl_Title {
            get {
                return ResourceManager.GetString("FormKayitOl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt sırasında beklenmedik bir hata oluştu:.
        /// </summary>
        internal static string GenelHata {
            get {
                return ResourceManager.GetString("GenelHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string HataBaslik {
            get {
                return ResourceManager.GetString("HataBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydınız başarıyla tamamlandı. Şimdi giriş yapabilirsiniz..
        /// </summary>
        internal static string KayitBasariliMesaj {
            get {
                return ResourceManager.GetString("KayitBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adı zaten alınmış. Lütfen farklı bir kullanıcı adı deneyin..
        /// </summary>
        internal static string KullaniciAdiMevcutHata {
            get {
                return ResourceManager.GetString("KullaniciAdiMevcutHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad:*.
        /// </summary>
        internal static string labelKayitAd {
            get {
                return ResourceManager.GetString("labelKayitAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta:.
        /// </summary>
        internal static string labelKayitEmail {
            get {
                return ResourceManager.GetString("labelKayitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı: *.
        /// </summary>
        internal static string labelKayitKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKayitKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre: *.
        /// </summary>
        internal static string labelKayitSifre {
            get {
                return ResourceManager.GetString("labelKayitSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar: *.
        /// </summary>
        internal static string labelKayitSifreTekrar {
            get {
                return ResourceManager.GetString("labelKayitSifreTekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad:*.
        /// </summary>
        internal static string labelKayitSoyad {
            get {
                return ResourceManager.GetString("labelKayitSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string labelKullaniciAdi {
            get {
                return ResourceManager.GetString("labelKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string labelSifre {
            get {
                return ResourceManager.GetString("labelSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz şifreler birbiriyle eşleşmiyor..
        /// </summary>
        internal static string SifreEslesmeHata {
            get {
                return ResourceManager.GetString("SifreEslesmeHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıldızlı (*) alanların tamamı doldurulmalıdır..
        /// </summary>
        internal static string ZorunluAlanlarHata {
            get {
                return ResourceManager.GetString("ZorunluAlanlarHata", resourceCulture);
            }
        }
    }
}
